Update gcp/ubuntu-c2r-dev
* Add new `warn()` that was missing from a previous commit

* Change `error()` to use string `Error:` instead of `error:`

diff --git a/gcp/ubuntu-c2r-dev b/gcp/ubuntu-c2r-dev
--- a/gcp/ubuntu-c2r-dev
+++ b/gcp/ubuntu-c2r-dev
@@ -142,10 +142,17 @@ function info()
 }
 ## }}}
 
+## {{{ warn()
+function warn()
+{
+  echo >&2 "$SCRIPT_NAME: Warning:" "$@"
+}
+## }}}
+
 ## {{{ error()
 function error()
 {
-  echo >&2 "$SCRIPT_NAME: error:" "$@"
+  echo >&2 "$SCRIPT_NAME: Error:" "$@"
 }
 ## }}}
 
